version: '3'

services:
  db:
    image: postgres:12
    container_name: node_worldcup
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=worldcup
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  app: 
    image: joseaugustooliveirapins/api-node-worldcup
    command: npm start
    ports: 
      - '8084:8084'
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db