name: Dockerize Node.js application

on: push

jobs:
  build-container:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image 
        uses: actions/checkout@v3
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: joseaugustooliveirapins/api-node-worldcup
          tags: latest, ${{ github.run_number }}